language : node_js

node_js : 
  - stable

install : 
  - npm install

script : 
  - npm run cover

# send coverage data to Coveralls
after_script : "cat coverage/icov.info | node_modules/coveralls/bin/coveralls.js"
